-- MySQL Script generated by MySQL Workbench
-- Thu Jan 12 20:02:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas` (
  `Turno` INT NOT NULL,
  `Quant. de Alunos` VARCHAR(45) NULL,
  PRIMARY KEY (`Turno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alunos` (
  `Nome` INT NOT NULL,
  `Data de Nasc.` VARCHAR(45) NULL,
  `Alunos_Nome` INT NOT NULL,
  PRIMARY KEY (`Nome`, `Alunos_Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `Nome do Curso` INT NOT NULL,
  `Professor` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  `Turmas_Turno` INT NOT NULL,
  `Alunos_Nome` INT NOT NULL,
  `Alunos_Alunos_Nome` INT NOT NULL,
  PRIMARY KEY (`Nome do Curso`, `Turmas_Turno`, `Alunos_Nome`, `Alunos_Alunos_Nome`),
  INDEX `fk_Cursos_Turmas1_idx` (`Turmas_Turno` ASC) VISIBLE,
  INDEX `fk_Cursos_Alunos1_idx` (`Alunos_Nome` ASC, `Alunos_Alunos_Nome` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_Turmas1`
    FOREIGN KEY (`Turmas_Turno`)
    REFERENCES `mydb`.`Turmas` (`Turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cursos_Alunos1`
    FOREIGN KEY (`Alunos_Nome` , `Alunos_Alunos_Nome`)
    REFERENCES `mydb`.`Alunos` (`Nome` , `Alunos_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turmas_has_Alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turmas_has_Alunos` (
  `Turmas_Turno` INT NOT NULL,
  `Alunos_Nome` INT NOT NULL,
  `Alunos_Alunos_Nome` INT NOT NULL,
  PRIMARY KEY (`Turmas_Turno`, `Alunos_Nome`, `Alunos_Alunos_Nome`),
  INDEX `fk_Turmas_has_Alunos_Alunos1_idx` (`Alunos_Nome` ASC, `Alunos_Alunos_Nome` ASC) VISIBLE,
  INDEX `fk_Turmas_has_Alunos_Turmas1_idx` (`Turmas_Turno` ASC) VISIBLE,
  CONSTRAINT `fk_Turmas_has_Alunos_Turmas1`
    FOREIGN KEY (`Turmas_Turno`)
    REFERENCES `mydb`.`Turmas` (`Turno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turmas_has_Alunos_Alunos1`
    FOREIGN KEY (`Alunos_Nome` , `Alunos_Alunos_Nome`)
    REFERENCES `mydb`.`Alunos` (`Nome` , `Alunos_Nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
